image: node:16.14.0
pipelines:
 branches:
   master:
     - step:
         script:
            - npm install
            - npm run build
            - git push https://heroku:f08f9c76-8199-42e8-9624-575f6f669e06@git.heroku.com/dinh-react-cicd.git HEAD